AssertionError: Add information about assertion source location (macros)
It is nice to see where the assertion came from.
Now name of file, source line and function/method name are passed
with the assertion.

`std::source_location` has been supported since C++20 and is not yet
implemented in Clang. So the only solution is to use __FILE__, __LINE__,
__PRETTY_FUNCTION__/__func__.

Functions that desire to obtain this information about the call site
must use macros so that predefined macros like __LINE__ are expanded
in the context of the caller.